apiVersion: batch/v1
kind: Job

metadata:
  name: dcb-playwright

spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed
  backoffLimit: 0

  template:
    metadata:
      labels:
        app: dcb-playwright

    spec:
      restartPolicy: Never

      containers:
        - name: dcb-test
          image: dcb:1.0
          imagePullPolicy: IfNotPresent

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']

          command:
            - /bin/sh
            - -c

          args:
            - |
              echo "=================================="
              echo "Pod: $POD_NAME"
              echo "Shard Index: $JOB_COMPLETION_INDEX"
              echo "=================================="

              if [ "$JOB_COMPLETION_INDEX" = "0" ]; then

                echo "Running SHARD 1"

                dotnet test \
                  /app/Framework.Tests/bin/Debug/net10.0/Framework.Tests.dll \
                  --filter "Category=Shard1"

              elif [ "$JOB_COMPLETION_INDEX" = "1" ]; then

                echo "Running SHARD 2"

                dotnet test \
                  /app/Framework.Tests/bin/Debug/net10.0/Framework.Tests.dll \
                  --filter "Category=Shard2"

              elif [ "$JOB_COMPLETION_INDEX" = "2" ]; then

                echo "Running SHARD 3"

                dotnet test \
                  /app/Framework.Tests/bin/Debug/net10.0/Framework.Tests.dll \
                  --filter "Category=Shard3"

              else

                echo "Unknown shard index: $JOB_COMPLETION_INDEX"
                exit 1

              fi
