apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcb-playwright
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dcb-playwright
  template:
    metadata:
      labels:
        app: dcb-playwright
    spec:
      containers:
        - name: dcb-test
          image: dcb:1.0
          imagePullPolicy: IfNotPresent
